name: kibisis
description: "Kibisis Mobile App"
publish_to: 'none'
version: 1.0.0+10000010
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.6
  go_router: ^13.2.2
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  ellipsized_text: ^1.2.0
  cupertino_icons: ^1.0.6
  algorand_dart: ^1.0.3
  gradient_borders: ^1.0.0
  flutter_secure_storage: ^9.0.0
  convert: ^3.1.1
  crypto: ^3.0.1
  flutter_native_splash: ^2.4.0
  qr_flutter: ^4.1.0
  top_snackbar_flutter: ^3.1.0
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.3
  image_gallery_saver: ^2.0.3
  share_plus: ^9.0.0
  permission_handler: ^11.3.1
  infinite_carousel: ^1.1.1
  vibration: ^1.8.4
  percent_indicator: ^4.2.3
  http: ^1.2.2
  card_swiper: ^3.0.1
  base32: ^2.1.3
  connectivity_plus: ^6.0.5
  flutter_expandable_fab: ^2.2.0
  dio: ^4.0.6
  cryptography: ^2.7.0
  mobile_scanner: ^5.1.1
  intl: ^0.19.0
  infinite_scroll_pagination: ^4.0.0
  flutter_confetti: ^0.3.0
  reown_walletkit: ^1.0.1
dependency_overrides:
  win32: 5.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  commitlint_cli: ^0.7.1
  husky: ^0.1.7
  test: ^1.24.9
flutter_native_splash:
  color: "#1A202C"
  image: "assets/images/splash-logo.png"
  android_12:
    image: "assets/images/splash-logo.png"
    color: "#1A202C"
  android: true
  ios: true
  web: true
  fullscreen: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FF8D029B"
    theme_color: "#FFFFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: 'Nunito'
      fonts:
        - asset: 'assets/fonts/Nunito/Nunito-Regular.ttf'
        - asset: 'assets/fonts/Nunito/Nunito-Bold.ttf'
          weight: 700
